/*
 * Copyright (C) 2018 chymes.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package org.hymesruzicka.maptool.tools.token;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.hymesruzicka.maptool.tools.ZipWrangler;
import static rptools.maptool.campaign.content.DandDDadsProperiesText.DEFAULT_NPC_CIVILIAN_FILE;

/**
 *
 * @author chymes
 */
public class TokenProcessingFrame extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(TokenProcessingFrame.class.getName());

    /**
     * Creates new form TokenProcessingFrame
     */
    public TokenProcessingFrame() {
        initComponents();
    }

    private TokenProcessingFrame init() {
        /**
         * After construction, and on the EDT*
         */
        sourcejTextField.setText(ZipWrangler.CAMPAIGN_ORIGIONAL_DIR_NAME);
        replacementjTextField.setText(DEFAULT_NPC_CIVILIAN_FILE.toString());
        destinationjTextField.setText(ZipWrangler.WORK_DIR_NAME);
        resultjTextField.setVisible(false);
        setEnabledAll(true);
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourcejLabel = new javax.swing.JLabel();
        sourcejTextField = new javax.swing.JTextField();
        destinationjLabel = new javax.swing.JLabel();
        destinationjTextField = new javax.swing.JTextField();
        chooseSourcejButton = new javax.swing.JButton();
        chooseDestinationjButton = new javax.swing.JButton();
        commencejButton = new javax.swing.JButton();
        replacementjLabel = new javax.swing.JLabel();
        replacementjTextField = new javax.swing.JTextField();
        chooseReplacementjButton = new javax.swing.JButton();
        resultjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sourcejLabel.setLabelFor(sourcejTextField);
        sourcejLabel.setText("Source file or directory of campaign content:");
        sourcejLabel.setToolTipText("The cmpgn file or directory that contains the content.xml file");

        sourcejTextField.setText("<unset>");

        destinationjLabel.setLabelFor(destinationjTextField);
        destinationjLabel.setText("Destination directory:");
        destinationjLabel.setToolTipText("This is where a copy of the campaign archive will be written.");

        destinationjTextField.setText("<unset>");

        chooseSourcejButton.setText("...");
        chooseSourcejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSourcejButtonActionPerformed(evt);
            }
        });

        chooseDestinationjButton.setText("...");
        chooseDestinationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDestinationjButtonActionPerformed(evt);
            }
        });

        commencejButton.setText("Process Campaign Tokens");
        commencejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commencejButtonActionPerformed(evt);
            }
        });

        replacementjLabel.setLabelFor(sourcejTextField);
        replacementjLabel.setText("Replacement XML file:");
        replacementjLabel.setToolTipText("The directory or archive that contains the content.xml file");

        replacementjTextField.setText("<unset>");

        chooseReplacementjButton.setText("...");
        chooseReplacementjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseReplacementjButtonActionPerformed(evt);
            }
        });

        resultjTextField.setEditable(false);
        resultjTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        resultjTextField.setText("nofink");
        resultjTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 0), new java.awt.Color(0, 204, 51)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(commencejButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(destinationjTextField)
                                    .addComponent(sourcejTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chooseSourcejButton)
                                    .addComponent(chooseDestinationjButton))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourcejLabel)
                            .addComponent(destinationjLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(replacementjTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseReplacementjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(replacementjLabel)
                        .addGap(332, 332, 332))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourcejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourcejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseSourcejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(replacementjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replacementjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseReplacementjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(destinationjLabel)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseDestinationjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commencejButton)
                    .addComponent(resultjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseSourcejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSourcejButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Zip & Campaign files", "zip", "cmpgn");
        Path parent = Paths.get(sourcejTextField.getText()).getParent();
        chooser.setCurrentDirectory(parent.toFile());
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            LOG.log(Level.INFO, "Source for campaign data = {0}", chooser.getSelectedFile().getName());
            sourcejTextField.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_chooseSourcejButtonActionPerformed

    private void chooseDestinationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDestinationjButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setCurrentDirectory(new java.io.File(destinationjTextField.getText()));
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            LOG.log(Level.INFO, "Destination for campaign file = {0}", chooser.getSelectedFile().getName());
            destinationjTextField.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_chooseDestinationjButtonActionPerformed

    private void commencejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commencejButtonActionPerformed
        TokenWorker worker = new TokenWorker(this, sourcejTextField.getText(), replacementjTextField.getText(), destinationjTextField.getText());
        LOG.log(Level.FINE, "Button pushed.");
        worker.addPropertyChangeListener(listener -> putOut(worker));
        setEnabledAll(false);
        worker.execute();
        worker.requestPatience();
    }//GEN-LAST:event_commencejButtonActionPerformed

    private void chooseReplacementjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseReplacementjButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Replacement XML file", "xml");
        Path parent = Paths.get(replacementjTextField.getText()).getParent();
        chooser.setCurrentDirectory(parent.toFile());
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            LOG.log(Level.INFO, "Source for XML replacement data = {0}", chooser.getSelectedFile().getName());
            replacementjTextField.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_chooseReplacementjButtonActionPerformed

    private void setEnabledAll(boolean value) {
        chooseDestinationjButton.setEnabled(value);
        chooseReplacementjButton.setEnabled(value);
        chooseSourcejButton.setEnabled(value);
        commencejButton.setEnabled(value);
        destinationjTextField.setEnabled(value);
        replacementjTextField.setEnabled(value);
        sourcejTextField.setEnabled(value);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokenProcessingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokenProcessingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokenProcessingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokenProcessingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TokenProcessingFrame guiFrame = new TokenProcessingFrame();
                guiFrame.init();
                guiFrame.setVisible(true);
            }
        });
    }

    private void putOut(TokenWorker worker) {
        if (worker.isDone()) {
            try {
                resultjTextField.setText(worker.get());
            } catch (InterruptedException | ExecutionException ex) {
                LOG.log(Level.SEVERE, null, ex);
            }
            resultjTextField.setVisible(true);
            setEnabledAll(true);
            revalidate();
            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseDestinationjButton;
    private javax.swing.JButton chooseReplacementjButton;
    private javax.swing.JButton chooseSourcejButton;
    private javax.swing.JButton commencejButton;
    private javax.swing.JLabel destinationjLabel;
    private javax.swing.JTextField destinationjTextField;
    private javax.swing.JLabel replacementjLabel;
    private javax.swing.JTextField replacementjTextField;
    private javax.swing.JTextField resultjTextField;
    private javax.swing.JLabel sourcejLabel;
    private javax.swing.JTextField sourcejTextField;
    // End of variables declaration//GEN-END:variables
}
